version: "3.9"

services:
  react-native:
    image: utkusarioglu/react-native-android-devcontainer:1.0.15
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/trials/rn-18/android
      - type: volume
        source: ccache
        target: /ccache
      - type: volume
        source: gradle
        target: /home/rn/.gradle
      - type: volume
        source: android
        target: /opt/android

volumes:
  ccache:
    name: react-native-ccache
  gradle:
    name: react-native-gradle

  android:
    name: react-native-android
