version: "3.9"

services:
  react-native:
    image: utkusarioglu/react-native-android-devcontainer:1.0.13
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/trials/rn-18/android
      # - type: bind
      #   source: ../../hooks
      #   target: /utkusarioglu/trials/rn-18/common
      #   read_only: true
      #   volume:
      #     nocopy: true
      - type: volume
        source: ccache
        target: /ccache
      - type: volume
        source: gradle
        target: /root/.gradle
      # - type: volume
      #   source: android-ndk
      #   target: /opt/android/ndk/21.4.7075529/toolchains/llvm/prebuilt
      - type: volume
        source: android
        target: /opt/android

volumes:
  ccache:
    name: react-native-ccache
  gradle:
    name: react-native-gradle

  # android-ndk:
  #   name: react-native-android-ndk-prebuilt

  android:
    name: react-native-android
